path_to_encoded_data: encoded_test_data.pt
path_to_model: model_mlp.pt
save_scores_path: scores.json

s3:
  bucket: task-ai-creator
  path_to_download: encodeds/encoded_test_data.pt
  path_to_upload: scores/scores.json

mlflow:
  experiment_name: "mlp_task_classifier"
  run_name: "baseline_v3"
  uri: "http://127.0.0.1:5000"

init_params:
  bert_model: DeepPavlov/rubert-base-cased
  batch_size: 32
  num_workers: 1
